config/routes.rb
Rails.application.routes.draw do
 devise_for :users
 root to: 'homes#top'
 resources :books
 get 'home/about' => 'homes#about'
 resources :users, only: [:show, :edit, :update, :index, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body,  presence: true, length: {maximum:200}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, uniqueness: true, length: {in: 2..20}
  validates :introduction, length: {maximum:50}

  has_many :books, dependent: :destroy
  attachment :profile_image

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_action :authenticate_user!,except: [:top, :about]

 before_action :configure_permitted_parameters, if: :devise_controller?

def after_sign_in_path_for(resource)
    user_path(resource.id)
end

def after_sign_out_path_for(resource)
    root_path
end
private

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,keys:[:email])
      devise_parameter_sanitizer.permit(:account_update,keys:[:introduction, :profile_image])
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def create
    @books = Book.all
    @new_book = Book.new(book_params)
    @user = User.find_by(id: current_user)
    @users = User.all
    @new_book.user_id = current_user.id
    if @new_book.save
     flash[:finger] = 'successfully'
     redirect_to book_path(@new_book)
    else
     render :index
    end
  end

  def index
    @new_book = Book.new
    @books = Book.all
    @user = User.find_by(id: current_user)
    @users = User.all
  end

  def show
    @book = Book.find(params[:id])
    @new_book = Book.new
    @user = User.find_by(id: @book.user_id)
  end

  def edit
    @book = Book.find(params[:id])
    unless @book.user == current_user
        redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
     if @book.user != current_user
      redirect_to  books_path
     else
      if
         @book.update(book_params)
         flash[:thumb] = 'successfully'
         redirect_to book_path(@book)
      else
       render :edit
      end
     end
  end

  def destroy
    @book = Book.find(params[:id])
    if @book.user != current_user
      redirect_to  books_path
    else
      @book.destroy
      redirect_to books_path
    end
  end

 private

  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
     @users = User.all
     @user = User.find(params[:id])
     @books = @user.books.page(params[:page])
     @new_book = Book.new
  end

  def index
    @users = User.all
    @books = Book.all
    @new_book = Book.new
    @user = User.find_by(id: current_user)
  end

  def create
    @books = Book.all
    @new_book = Book.new(book_params)
    @new_book.user_id = current_user.id
    if @new_book.save
     flash[:finger] = 'successfully'
     redirect_to book_path(@new_book)
    else
     render :"book/index"
    end
    @user = User.new(user_params)
    @book.user_id = current_user.id
    @user.save
    redirect_to books_path
  end

  def edit
     @user = User.find(params[:id])
     unless @user == current_user
       redirect_to user_path(current_user)
     end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
       flash[:thumb] = 'successfully'
       redirect_to user_path(@user.id)
    else
       render :edit
    end

  end

  def destroy
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_info.html.erb
 <div class="col-md-3">
 <h2>User info</h2>
 <%= attachment_image_tag user ,:profile_image, :fill, 63, 63, format: 'jpeg', fallback:"-user-icon.jpeg" %>
<table class="table">
  <tbody>
  <tr>
	  <th>name</th>

	  <th><%= user.name %></th>

  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
</tbody>
</table>
<div class="row">

  <%= link_to "", edit_user_path(user), class:'btn btn-outline-secondary btn-block fas fa-user-cog' %>

</div>
     <h2 class="mt-3">New book</h2>
   <%= form_with model:new_book, local:true do |f| %>
  <div class="form-group">
    <%= f.label :Title %><br />
      <%= f.text_field :title, class:'form-control book_title' %>
  </div>
  <div class="form-group">
      <%= f.label :Opinion %><br />
      <%= f.text_area :body, class:'form-control book_body' %>

  </div>
  <div class="form-group">
    <%= f.submit 'Create Book', class:'btn btn-success' %>
  </div>
  <% end %>
</div>

app/views/books/edit.html.erb
<%= flash[:thumb] %>
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
 <p id="notice"></p>
        <div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
   <%= form_with model:@book, local:true do |f| %>
   <div class="form-group">
       <%= f.label :Title %><br />
       <%= f.text_field :title, class:'form-control introduction' %>
   </div>
   <div class="form-group">
       <%= f.label :Opinion %><br />
       <%= f.text_area :body, class:'form-control introduction' %>
   </div>
   <div class="form-group">
          <%= f.submit 'Update Book', class:'btn btn-success' %>
   </div>

<% end %>
  		<%= link_to "Show", book_path(@book) %> |
  		<%= link_to "Back", books_path %>
  </div>
</div>
      </div>
      </main>

app/views/books/index.html.erb
<p id="notice"></p>
<% if @new_book.errors.any? %>
  <%= @new_book.errors.count %>errors prohibited this obj from being saved:
  <% @new_book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
<div class="container px-5 px-sm-0">
 <div class="row">
 <div class="col-md-3">
 <h2>User info</h2>
  <%= attachment_image_tag @user ,:profile_image, :fill, 63, 63, format: 'jpeg', fallback:"-user-icon.jpeg" %>
  <table class="table">
  <tbody><tr></tr>
  <tr>
	  <th>name</th>

	  <th><%= @user.name %></th>

  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= @user.introduction %></th>
  </tr>
</tbody>
</table>
<div class="row">
  <%= link_to "", edit_user_path(@user), class:'btn btn-outline-secondary btn-block fas fa-user-cog' %>
</div>
<h2 class="mt-3">New book</h2>
   <%= form_with model:@new_book, local:true do |f| %>
  <div class="form-group">
    <%= f.label :Title %><br />
      <%= f.text_field :title, class:'form-control book_title' %>
  </div>
  <div class="form-group">
      <%= f.label :Opinion %><br />
      <%= f.text_area :body, class:'form-control book_body' %>

  </div>
  <div class="form-group">
    <%= f.submit 'Create Book', class:'btn btn-success' %>
  </div>
  <% end %>
</div>


<div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <% @books.each do |book| %>
  <tbody>
   <td>
   <%= link_to user_path(book.user.id) do %>
   <%= attachment_image_tag book.user ,:profile_image, :fill, 40, 40, format: 'jpeg', fallback:"-user-icon.jpeg" %>
   <% end %>
   </td>
    <td><%= link_to book.title,book_path(book.id) %></td>
   <td>
     <%= book.body %>
   </td>
  </tbody>
  <% end %>
</table>
</div>
</div>
</div>

app/views/books/show.html.erb
<p id="notice"></p>
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
<div class="container px-5 px-sm-0">
 <div class="row">

<%= render 'books/info', user: @user, book: @book, new_book: @new_book %>


<div class="col-md-8 offset-md-1">
 <h2>Book detail</h2>
  <table class="table">

   <tbody>
     <tr>
       <td>
        <%= link_to user_path(@book.user.id) do %>
        <%= attachment_image_tag @user ,:profile_image, :fill, 40, 40, format: 'jpeg', fallback:"-user-icon.jpeg" %><br>
            <%= @book.user.name %>
        <% end %>
        </a>
       </td>
       <td>
        <%= link_to @book.title, book_path(@book.id) %>
       </td>
       <td>
         <%= @book.body %>
       </td>
       <% if @book.user == current_user %>
        <td><%= link_to "Edit", edit_book_path(@book), "class" =>"btn btn-sm btn-success" %></td>
        <td><%= link_to "Destroy", book_path(@book), method: :delete, "data-confirm" => "本当に削除しますか？", "class" => "btn btn-sm btn-danger" %></td>
       <% end %>
      </tr>
    </tbody>

   </table>

 </div>
 </div>
 </div>

app/views/homes/about.html.erb
<p id="notice"></p>
  <div class="container">
   <div class="row">
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
   </div>
  </div>

app/views/homes/top.html.erb
<p id="notice"></p>
 <div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in", '/users/sign_in', class:'btn btn-info btn-sm btn-block mb-3 sign_in' %>
        </div>
        <div class="row">
          <%= link_to "Sign up", '/users/sign_up', class:'btn btn-success btn-sm btn-block sign_up' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_notifications.html.erb
<div class="Notification">
 <% flash.each do |key, value| %>
 <%= content_tag :div, value, class: key %>

 <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  </head>
  <header>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
       <a class="navbar-brand" href="/"><span>Bookers</span></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
        </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
       <ul class="navbar-nav ml-auto">
         <% if user_signed_in? %>
         <li>
          <%= link_to "Home", user_path(current_user.id), class:'fas fa-home nav-link text-light' %>
        </li>
        <li>
         <%= link_to "Users", users_path, class:'fas fa-users nav-link text-light' %>
        </li>
        <li>
         <%= link_to "Books", books_path, class:'fas fa-book-open nav-link text-light' %>
        </li>
        <li>
         <%= link_to "Log out", destroy_user_session_path, method: :delete, class:'fas fa-sign-out-alt nav-link text-light' %>
        </li>
       </ul>
      </div>
      </div>
    </nav>
    <% else %>
          <li>
            <%= link_to "Home", root_path, class:'fas fa-home nav-link text-light' %>
          </li>
          <li>
            <a class="fas fa-link nav-link text-light" href="/home/about"> About</a>
          </li>
          <li>
            <%= link_to "Sign up", '/users/sign_up', class:'fas fa-user-plus nav-link text-light' %>
          </li>
          <li>
            <%= link_to "Log in", '/users/sign_in', class:'fas fa-sign-in-alt nav-link text-light' %>
          </li>
        </ul>
      </div>
      </div>
    </nav>
    <% end %>
  </header>
  <main>
    <%= render 'layouts/notifications' %>
    <%= yield %>
  </main>

  <footer>
   <div class="container mt-5">
    <div class="row">
      <div class="mx-auto">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
   </div>
  </footer>
</html>

app/views/users/edit.html.erb
<p id="notice"></p>
<% if @user.errors.any? %>
  <%= @user.errors.count %>errors prohibited this obj from being saved:
  <% @user.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>

     <div class="form-group">
      <%= f.label :Name %><br />
      <%= f.text_field :name, class:'form-control name' %>
     </div>
     <div class="form-group">

        <%= f.label :Image %><br />
         <%= f.attachment_field :profile_image %>
      </div>
      <div class="form-group">
       <%= f.label :Introduction %><br />
       <%= f.text_area :introduction, class:'form-control introduction' %>
      </div>
      <div class="form-group">
          <%= f.submit 'Update User', class:'btn btn-secondary' %>
      </div>
      <% end %>
</form>  </div>
</div>

      </div>

app/views/users/index.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
 <div class="row">

<%= render 'books/info', user: @user, book: @book, new_book: @new_book %>
<div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <% @users.each do |user| %>
      <tr>
        <td> <%= attachment_image_tag user ,:profile_image, :fill, 40, 40, format: 'jpeg', fallback:"-user-icon.jpeg" %></td>
        <td><%= user.name %></td>
        <td><%= link_to "Show",user_path(user.id) %></td>
      </tr>
      <% end %>
  </tbody>
</table>
</div>
</div>
</div>

app/views/users/show.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
 <div class="row">


<%= render 'books/info', user: @user, book: @book, new_book: @new_book %>

<div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <% @books.each do |book| %>

  <tbody>
   <td>
       <%= link_to user_path(@user) do %>
        <%= attachment_image_tag @user ,:profile_image, :fill, 40, 40, format: 'jpeg', fallback:"-user-icon.jpeg" %><br>
       <% end %>
   </td>
    <td><%= link_to book.title,book_path(book.id) %></td>
   <td>
     <%= book.body %>
   </td>
  </tbody>
  <% end %>
</table>
</div>
</div>
</div>